server:
  port: 8080
  uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esun_vote?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jdbc:
    template:
      fetch-size: 200
      max-rows: 10000

logging:
  level:
    org.springframework.jdbc.core: DEBUG

# 簡單 CORS（前端 Vite 預設 5173）
app:
  cors:
    allowed-origins: http://localhost:5173