spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esun_vote?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Taipei&useSSL=false&allowPublicKeyRetrieval=true
    username: YOUR_DB_USER
    password: YOUR_DB_PASSWORD
